language: python
sudo: required
services:
  - docker
matrix:
  include:
    - python: 2.7
      env: TOXENV="py27-tests,py27-lint,cli,coverage"
    - python: 3.4
      env: TOXENV="py34-tests,cli"
    - python: 3.5
      env: TOXENV="copying,py35-tests,py35-lint,cli,coverage"
    - python: 3.6
      env: TOXENV="py36-tests,cli"

before_install:
  - make generate
  - pip install tox

install:
  - pip install .

script:
  - tox
