language: python
dist: xenial

matrix:
  include:
    - python: 3.4
      env: TOXENV="py34-tests,cli"
    - python: 3.5
      env: TOXENV="copying,py35-tests,coverage_upload_tests,py35-tools,coverage_upload_tools,py35-lint,cli"
    - python: 3.6
      env: TOXENV="py36-tests,cli"
    - python: 3.7
      env: TOXENV="py37-tests,cli"

before_install:
  - pip install tox

install:
  - pip install .

script:
  - tox
